"""add 

Revision ID: 17f1ff2c8ea9
Revises: 6a5b8d52f042
Create Date: 2026-05-14 22:17:59.299982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f1ff2c8ea9'
down_revision = '6a5b8d52f042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('stripe_session_id')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
