"""worke

Revision ID: 3a5a0c7b7103
Revises: ac8da19da690
Create Date: 2026-05-21 22:59:34.311880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5a0c7b7103'
down_revision = 'ac8da19da690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_onboarding_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('stripe_onboarding_complete')

    # ### end Alembic commands ###
