"""stripe

Revision ID: 402abda401a5
Revises: 3a5a0c7b7103
Create Date: 2026-05-22 21:53:15.001496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402abda401a5'
down_revision = '3a5a0c7b7103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payout_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.drop_column('stripe_payout_id')

    # ### end Alembic commands ###
