"""requested workers

Revision ID: 50694a9c26c1
Revises: b6b865dd19d1
Create Date: 2026-05-17 22:52:03.301033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50694a9c26c1'
down_revision = 'b6b865dd19d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_worker_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('requested_worker_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_worker_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('requested_worker_id')

    # ### end Alembic commands ###
