"""add worker review

Revision ID: a48ead8ee069
Revises: 17372a431493
Create Date: 2026-05-13 19:16:09.167698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48ead8ee069'
down_revision = '17372a431493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_reviews', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('total_reviews')

    # ### end Alembic commands ###
