"""worker wallet system

Revision ID: ac8da19da690
Revises: 2143c49a5a80
Create Date: 2026-05-21 22:31:14.546126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8da19da690'
down_revision = '2143c49a5a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payout_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pending_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_lifetime_earnings', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('total_lifetime_earnings')
        batch_op.drop_column('pending_balance')
        batch_op.drop_column('available_balance')

    op.drop_table('payout_requests')
    # ### end Alembic commands ###
