"""add earnings columns

Revision ID: c61eef391654
Revises: 17f1ff2c8ea9
Create Date: 2026-05-15 19:14:57.538689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61eef391654'
down_revision = '17f1ff2c8ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_gross_earnings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_net_earnings', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('total_net_earnings')
        batch_op.drop_column('total_gross_earnings')

    # ### end Alembic commands ###
